---
title: "Download R Scripts"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The wonderful thing about R scripts is that once you create one for a task you can just keep on using it over and over for that task and share it others who use that task. 

The `englelab` package has a convenient function to download R scripts for the tasks we host on our [website](http://englelab.gatech.edu/taskdownloads){target="_blank"}

## `get_script()`

The first two agruments you should specify is the location you want to download the R Script to (by default set to "R Scripts") and the type of R Script you want to download.

- __to__: Save to a folder within your working directory (i.e. "R Scripts")

- __type__: You can download R Scripts:

    1. To create tidy raw data files from the messy E-Prime file. `type = "raw"`
    
    2. To create a scored data file from the tidy raw data file. `type = "score"`
    
Next, you will want to specify for which tasks you want to download R Scripts for. The options are:

- __wmc__: Download the scripts for operation span, symmetry span, and rotation span. `wmc = TRUE`

- __ospan__: Download the script for operatoin span. `ospan = TRUE`

- __symspan__: Download the script for symmetry span. `symspan = TRUE`

- __rotspan__: Download the script for rotation span. `rotspan = TRUE`

- __gf__: Download the scripts for ravens, number series, and lettersets `gf = TRUE`

- __rapm__: Download the script for ravens advanaced progressive matrices `rapm = TRUE`

- __numberseries__: Download the script for number series `numberseries = TRUE`

- __lettersets__: Download the script for letter sets `lettersets = TRUE`

- __ac__: Download the scripts for all attention control tasks `ac = TRUE`

- __antisaccade__: Download the script for the antisaccade. `antisaccade = TRUE`

- __va4__: Download the script for the visual arrays. `va4 = TRUE`

- __sact__: Download the script for the sustained attention to cue task. `sact = TRUE`

- __flankerDL__: Download the script for the adaptive flanker deadline. `flankerDL = TRUE`

- __stroopDL__: Download the script for the adaptive stroop deadline. `stroopDL = TRUE`

- __flanker__: Download the script for the traditional RT flanker. `flanker = TRUE`

- __stroop__: Download the script for the traditional RT stroop `stroop = TRUE`



