---
output: html_document
editor_options: 
  chunk_output_type: console
editor: visual
---

## Required Packages

------------------------------------------------------------------------

```{r}
#| eval: false

source("R/_required_packages.R")
```

## Data Preparation

------------------------------------------------------------------------

Create tidy raw data files from messy raw data files

-   **Import Directory**: data/raw/messy

-   **Output Directory**: data/raw

```{r}
source("R/1_task_raw.csv")

rm(list = ls())
```

## Data Scoring and Cleaning

------------------------------------------------------------------------

Create scored and cleaned data files from raw data files

-   **Import Directory**: data/raw

-   **Output Directory**: data/scored

-   **Data Cleaning**: A log of which subjects were removed for each task due to data cleaning can be found in data/**logs**

```{r}
source("R/2_task_score.R")

rm(list = ls())
```

Create merged data files ready for statistical analysis from scored data files

**Import Directory**: data/scored

**Output Directory**: data

```{r}
source("R/3_merge.R")

rm(list = ls())
```

## Statistical Analysis and Data Visualization

------------------------------------------------------------------------

Perform statistical analysis and create data visualizations

Output is saved as **.html** files to **analyses/**

```{r}
library(quarto)

quarto_render("analyses/Analysis.qmd")

rm(list = ls())
```
